config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/contact_me', to: 'static_pages#contact_me', as: :contact

  get '/About_me', to: 'static_pages#About_me', as: :about

  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
   @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    if @post.save
    redirect_to post_path(@post)
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
    redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :author, :body)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact_me
  end

  def about_me
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %> |
<%= link_to 'About', about_path %> |
<%= link_to 'Contact Me', contact_path %> |
<%= link_to 'Posts', posts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navbar' %>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit %>

<%end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>
<%= link_to 'Edit', edit_post_path(@post) %>

app/views/posts/index.html.erb
<h1>All Posts</h1>
<% @posts.each do |post| %>
  <h1><%= post.title %></h1>
  <h1><%= post.author %></h1>
  <p>
    <%= post.body %>
  </p>
  <%= link_to 'Show', post_path(post) %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<h1>My Post</h1>

<h1><%= @post.title %></h1>
<h1><%= @post.author %></h1>
<p>
  <%= @post.body %>
</p>

<%= link_to 'Back', posts_path %>
<%= link_to 'Edit', edit_post_path(@post) %>
<%= link_to 'Destroy Post', @post, method: :delete %>

app/views/static_pages/About_me.html.erb
<h1>About_me</h1>

<!doctype html>
<html>
  <head>
    <title>About Me</title>
    <link rel="stylesheet" type="text/css" href="style.css">
  </head>


  <body>
    <div id="wrapper">

      <div id="header">
        <header>
          <h1>Evan Allred</h1>
        </header>
      </div>

      <div id="content">
        <div class="profile_pic">
          <img src="img/evan_allred.jpg">
        </div>
        <div class="info">
          <ul>
            <li>From -<span>Rocky Ridge, Utah. (South of Santaquin)</span></li>
            <br>
            <li>Age -<span>24 yrs and counting</span></li>
            <br>
            <li>Profession -<span> 3D Modeler @ <a href="http://www.3dsbim.com">3DS Consulting.</a></span></li>


          </ul>
        </div>
        <div class="about_me">
          <h3 class="header"> A Little Bit About Me</h3>
          <p>I was born and raised here in Utah. I grew up roaming the mountains, I love Archery Hunting, Fishing, Football, Legos, Quadcopters, Science and my Family. I have always loved fixing things and creative construction.<br>
          I did commercial construction for 7 years before teaching myself 3D software</p>
        </div>
      </div>

      <div id="footer">
        <footer>
          <div>
            <p> I'm <strong>Super</strong> excited to be here to learn programming and web development!!</p>
          </div>
        </footer>
      </div>

    </div>
  </body>
</html>

app/views/static_pages/contact_me.html.erb
<h1>Contact Me</h1>

app/views/static_pages/home.html.erb
<div id="about_me">
  <h1> Home </h1>
    <nav >
      <div>
        <p><%= link_to 'About Me', about_path %></p>
        <p><%= link_to 'Posts', posts_path %></p>
      </div>
    </nav>

  <h3>Hello my name is Evan, welcome to awesomeness in the future.</h3>


  <div>
  What i do every day
    <ul>
      <li> play around at DevPoint</li>
      <li> play around at Home</li>
      <li> play around in the Mountains</li>
    </ul>
  </div>
</div>